# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-21 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('A', 'Activo'), ('C', 'Cancelado'), ('F', 'Finalizado')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
